# Generated by Django 4.2.5 on 2023-12-01 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articolo_visualizzaioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
