# Generated by Django 4.2.5 on 2023-12-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articolo_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='visualizzaioni',
            new_name='visualizzazioni',
        ),
    ]
